name: Generate Documentation

on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Delete previous documentation
      run: |
            rm -rf docs

    - name: Generate typedoc documentation
      run: pnpm run docs

    - name: Add documentation to commit
      run: |
            git add docs
            git commit -m "Update documentation"
